- name: Install common
  hosts: docker_swarm_manager:docker_swarm_worker
  environment: "{{ env_vars|default({}) }}"
  gather_facts: no
  tasks:
    - import_role:
        name: windows/gather-facts
      tags:
        - gather_facts
    - import_role:
        name: windows/common
      tags:
        - common
        - gather_facts
