- name: Install  registry Container
  hosts: docker_swarm_manager
  environment: "{{ env_vars|default({}) }}"
  gather_facts: no
  tasks:
    - import_role:
        name: windows/gather-facts
      tags:
        - gather_facts
    - import_role:
        name: windows/registry
      tags:
        - registry
        - gather_facts
